// --------------Project Tasks
// Create a Landing Page.................[COMPLETED]
// Create a Feed.........................[]
// Create a User Profile.................[]
// Create a Politician Profile...........[]
// Create an Explore Page................[]
// Implement Post Creation...............[]
// Make a Chat interface.................[]
// Implement a Search Bar................[]
// Set up the back-end server............[]
